In [7]:
! kaggle datasets download -d shrutimehta/nasa-asteroids-classification

  0% 0.00/3.27M [00:00<?, ?B/s]
100% 3.27M/3.27M [00:00<00:00, 105MB/s]


In [ ]:
!unzip \*.zip

In [60]:
import pandas as pd

In [61]:
df = pd.read_csv('/content/nasa.csv')

In [62]:
df.head(10)

Neo Reference ID     Name  ...  Equinox  Hazardous
0           3703080  3703080  ...    J2000       True
1           3723955  3723955  ...    J2000      False
2           2446862  2446862  ...    J2000       True
3           3092506  3092506  ...    J2000      False
4           3514799  3514799  ...    J2000       True
5           3671135  3671135  ...    J2000      False
6           2495323  2495323  ...    J2000      False
7           2153315  2153315  ...    J2000      False
8           2162463  2162463  ...    J2000      False
9           2306383  2306383  ...    J2000       True

[10 rows x 40 columns]

In [63]:
df.columns

Index(['Neo Reference ID', 'Name', 'Absolute Magnitude', 'Est Dia in KM(min)',
       'Est Dia in KM(max)', 'Est Dia in M(min)', 'Est Dia in M(max)',
       'Est Dia in Miles(min)', 'Est Dia in Miles(max)',
       'Est Dia in Feet(min)', 'Est Dia in Feet(max)', 'Close Approach Date',
       'Epoch Date Close Approach', 'Relative Velocity km per sec',
       'Relative Velocity km per hr', 'Miles per hour',
       'Miss Dist.(Astronomical)', 'Miss Dist.(lunar)',
       'Miss Dist.(kilometers)', 'Miss Dist.(miles)', 'Orbiting Body',
       'Orbit ID', 'Orbit Determination Date', 'Orbit Uncertainity',
       'Minimum Orbit Intersection', 'Jupiter Tisserand Invariant',
       'Epoch Osculation', 'Eccentricity', 'Semi Major Axis', 'Inclination',
       'Asc Node Longitude', 'Orbital Period', 'Perihelion Distance',
       'Perihelion Arg', 'Aphelion Dist', 'Perihelion Time', 'Mean Anomaly',
       'Mean Motion', 'Equinox', 'Hazardous'],
      dtype='object')

In [64]:
df.shape

(4687, 40)

In [65]:
print(df.isnull().sum())

Neo Reference ID                0
Name                            0
Absolute Magnitude              0
Est Dia in KM(min)              0
Est Dia in KM(max)              0
Est Dia in M(min)               0
Est Dia in M(max)               0
Est Dia in Miles(min)           0
Est Dia in Miles(max)           0
Est Dia in Feet(min)            0
Est Dia in Feet(max)            0
Close Approach Date             0
Epoch Date Close Approach       0
Relative Velocity km per sec    0
Relative Velocity km per hr     0
Miles per hour                  0
Miss Dist.(Astronomical)        0
Miss Dist.(lunar)               0
Miss Dist.(kilometers)          0
Miss Dist.(miles)               0
Orbiting Body                   0
Orbit ID                        0
Orbit Determination Date        0
Orbit Uncertainity              0
Minimum Orbit Intersection      0
Jupiter Tisserand Invariant     0
Epoch Osculation                0
Eccentricity                    0
Semi Major Axis                 0
Inclination   

In [66]:
correlation = df.corr(method='pearson')['Hazardous']
correlation

Neo Reference ID               -0.269028
Name                           -0.269028
Absolute Magnitude             -0.325522
Est Dia in KM(min)              0.132424
Est Dia in KM(max)              0.132424
Est Dia in M(min)               0.132424
Est Dia in M(max)               0.132424
Est Dia in Miles(min)           0.132424
Est Dia in Miles(max)           0.132424
Est Dia in Feet(min)            0.132424
Est Dia in Feet(max)            0.132424
Epoch Date Close Approach      -0.079020
Relative Velocity km per sec    0.191970
Relative Velocity km per hr     0.191970
Miles per hour                  0.191970
Miss Dist.(Astronomical)        0.032407
Miss Dist.(lunar)               0.032407
Miss Dist.(kilometers)          0.032407
Miss Dist.(miles)               0.032407
Orbit ID                        0.247369
Orbit Uncertainity             -0.328721
Minimum Orbit Intersection     -0.288949
Jupiter Tisserand Invariant    -0.003404
Epoch Osculation                0.040940
Eccentricity    

In [67]:
# Dropping all columns with same correlation

dataset = df[['Est Dia in KM(min)', 'Est Dia in KM(max)', 'Relative Velocity km per sec', 'Miss Dist.(kilometers)',
             'Orbit Uncertainity', 'Minimum Orbit Intersection', 'Eccentricity', 'Perihelion Distance', 'Aphelion Dist', 'Hazardous']]

In [68]:
dataset.columns

Index(['Est Dia in KM(min)', 'Est Dia in KM(max)',
       'Relative Velocity km per sec', 'Miss Dist.(kilometers)',
       'Orbit Uncertainity', 'Minimum Orbit Intersection', 'Eccentricity',
       'Perihelion Distance', 'Aphelion Dist', 'Hazardous'],
      dtype='object')

In [69]:
dataset.columns = ['Minimum Distance', 'Maximum Distance', 'Relative Velocity', 'Miss Distance', 'Orbit Uncertainity',
                   'Minimum Orbit Intersection', 'Eccentricity', 'Perihelion', 'Aphelion', 'Hazardous']

In [70]:
dataset.columns

Index(['Minimum Distance', 'Maximum Distance', 'Relative Velocity',
       'Miss Distance', 'Orbit Uncertainity', 'Minimum Orbit Intersection',
       'Eccentricity', 'Perihelion', 'Aphelion', 'Hazardous'],
      dtype='object')

In [71]:
import numpy as np

In [72]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [73]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
enc.fit_transform(y)

array([1, 0, 1, ..., 0, 0, 0])

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [75]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [76]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [77]:
prediction = classifier.predict(X_test)

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf = confusion_matrix(y_test, prediction)
acc = accuracy_score(y_test, prediction)
print(f'Confusion matrix is: \n { conf } \n Accuracy Score is: { acc }')

Confusion matrix is: 
 [[733  23]
 [ 77 105]] 
 Accuracy Score is: 0.8933901918976546


In [79]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [80]:
prediction = classifier.predict(X_test)

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf = confusion_matrix(y_test, prediction)
acc = accuracy_score(y_test, prediction)
print(f'Confusion matrix is: \n { conf } \n Accuracy Score is: { acc }')

Confusion matrix is: 
 [[731  25]
 [ 78 104]] 
 Accuracy Score is: 0.8901918976545842


In [82]:
from sklearn.svm import SVC

classifier = SVC(kernel = 'linear')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [83]:
prediction = classifier.predict(X_test)

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf = confusion_matrix(y_test, prediction)
acc = accuracy_score(y_test, prediction)
print(f'Confusion matrix is: \n { conf } \n Accuracy Score is: { acc }')

Confusion matrix is: 
 [[729  27]
 [ 72 110]] 
 Accuracy Score is: 0.894456289978678


In [85]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion='gini')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [86]:
prediction = classifier.predict(X_test)

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf = confusion_matrix(y_test, prediction)
acc = accuracy_score(y_test, prediction)
print(f'Confusion matrix is: \n { conf } \n Accuracy Score is: { acc }')

Confusion matrix is: 
 [[755   1]
 [ 40 142]] 
 Accuracy Score is: 0.9562899786780383


In [88]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=10)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [89]:
prediction = classifier.predict(X_test)

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score

conf = confusion_matrix(y_test, prediction)
acc = accuracy_score(y_test, prediction)
print(f'Confusion matrix is: \n { conf } \n Accuracy Score is: { acc }')

Confusion matrix is: 
 [[756   0]
 [ 42 140]] 
 Accuracy Score is: 0.9552238805970149
